@startuml
actor 用户
collections "收银台前端"
collections "收银台后端"
collections "PP"
collections "银联后端"

用户 -> "收银台后端" : 请求H5收银台
"收银台后端" -> "收银台后端" : 判断UA、产品开通等
"收银台后端" -> "银联后端" : 请求用户授权接口
"银联后端" -> "收银台后端" : 回调用户授权码
"收银台后端" --> "收银台前端" : 返回银联支付授权码
"收银台前端" -> "收银台后端" : 自动调用聚合支付下单接口，传入授权码
"收银台后端" -> "PP" : 请求授权码兑换userId接口
"PP" --> "收银台后端" : 返回userId
"收银台后端" -> "PP" : 请求聚合支付下单接口
"PP" --> "收银台后端" : 返回跳转地址
"收银台后端" --> "收银台前端" : 跳转到跳转地址
@enduml


@startuml
"商户" -> "API收银台" : 请求API银联JS支付
"API收银台" -> "API收银台" : 反查订单、产品开通等
"API收银台" -> "PP" : 请求用户授权接口
"PP" -> "FE" : 请求用户授权接口
"FE" -> "路由" : 请求用户授权接口
"路由" --> "FE" : 返回用户userId
"FE" --> "PP" : 返回用户userId
"PP" --> "API收银台" : 返回用户userId
"API收银台" -> "PP" : 请求支付下单接口
"PP" -> "FE" : 请求支付下单接口
"FE" -> "路由" : 请求支付下单接口
"路由" --> "FE" : 返回支付链接
"FE" --> "PP" : 返回支付链接
"PP" --> "API收银台" : 返回支付链接
"API收银台" --> "商户" : 返回API银联JS支付支付链接

@enduml
