@startuml
title 商户开户及绑卡
"商户" -> "新零售入网" : 商户入网
"新零售入网" -> "新零售入网" : 原有入网流程
"新零售入网" -> "前置通道" : 商户开户
"前置通道" -> "亿联银行" : 上传图片
"前置通道" <-- "亿联银行" : 返回图片ID
"前置通道" -> "亿联银行" : 请求亿联开户
"前置通道" <-- "亿联银行" : 开户成功，或受理成功(对公)
"新零售入网" <-- "前置通道" : 返回
"商户" <-- "新零售入网" : 返回入网结果


"新零售入网" -> "新零售入网" : 定时扫码受理成功请求(对公)
"新零售入网" -> "前置通道" : 查询开户状态(对公)
"前置通道" -> "亿联银行" : 查询开户状态(对公)
"前置通道" <-- "亿联银行" : 返回开户状态(对公)
"新零售入网" <-- "前置通道" : 返回开户状态(对公)

"新零售入网" -> "前置通道" : 绑定结算卡
"前置通道" -> "亿联银行" : 上传图片
"前置通道" <-- "亿联银行" : 返回图片ID
"前置通道" -> "亿联银行" : 请求亿联绑定结算卡
"前置通道" <-- "亿联银行" : 绑定成功，或受理成功(对公)
"新零售入网" <-- "前置通道" : 返回
"新零售入网" -> "新零售入网" : 定时扫码受理成功请求(对公)
"新零售入网" -> "前置通道" : 查询绑定状态(对公)
"前置通道" -> "亿联银行" : 查询绑定状态(对公)
"前置通道" <-- "亿联银行" : 返回绑定状态(对公)
"新零售入网" <-- "前置通道" : 返回绑定状态(对公)
"商户" <- "新零售入网" : 通知开户结果
@enduml

@startuml
title 商户提现
"商户" -> "出款" : 商户提现
"出款" -> "新零售入网" : 商户提现
"新零售入网" -> "前置通道" : 商户提现
"前置通道" -> "亿联银行" : 商户提现
"前置通道" <-- "亿联银行" : 返回商户提现结果
"新零售入网" <-- "前置通道" : 返回商户提现结果
"出款" <-- "新零售入网" : 返回商户提现结果
"商户" <-- "出款" : 返回商户提现结果
@enduml

@startuml
title 商户提现
"商户" -> "出款" : 查询账户余额
"出款" -> "新零售入网" : 查询账户余额
"新零售入网" -> "前置通道" : 查询账户余额
"前置通道" -> "亿联银行" : 查询亿联账户余额
"前置通道" <-- "亿联银行" : 返回查询结果
"新零售入网" <-- "前置通道" : 返回查询结果
"出款" <-- "新零售入网" : 返回查询结果
"商户" <-- "出款" : 返回查询结果
@enduml
