
@startuml
title H5收银台交互时序图
actor 用户
"用户" -> "服务商" : 去支付
"服务商" -> "OPR" : OPR下单
"OPR" --> "服务商" : 返回token
"服务商" -> "收银台" : 收银台标准链接
"收银台" -> "OPR" : 反查订单
"收银台" -> "收银台" : 产品校验等
"收银台" --> "用户" : 返回收银台(PC/H5)链接

"用户" -> "收银台" : 选择支付方式(微信公众号为例)
"收银台" -> "PP" : 预路由
"PP" -> "FE" : 预路由
"FE" -> "路由" : 预路由
"路由" --> "FE" : 预路由返回
"FE" --> "PP" : 预路由返回
"PP" --> "收银台" : 预路由返回
"收银台" -> "PP" : 支付下单
"PP" -> "FE" : 支付下单
"FE" -> "路由" : 支付下单
"路由" --> "FE" : 返回支付数据
"FE" --> "PP" : 返回支付数据
"PP" --> "收银台" : 返回支付数据
"收银台" --> "收银台" : 前端唤起支付
"用户" -> "用户" : 微信客户端确认支付
"用户" -> "用户" : 支付完成微信前端回调，成功则跳转支付查询页


"路由" -[#blue]> "FE" : (银行子系统)支付回调
"FE" -[#blue]> "PP" : 支付回调
"PP" -[#blue]> "PP" : 差错处理
"PP" -[#blue]> "OPR" : 支付回调
"PP" -[#blue]> "收银台" : 支付回调
"收银台" -[#blue]> "用户" : 页面监听到完成，跳转支付完成页
"OPR" -[#blue]> "OPR" : 计费入账等资金处理
"OPR" -[#blue]> "服务商" : 支付回调
@enduml

@startuml
title 聚合支付API交互时序图
actor 服务商
"服务商" -> "OPR" : OPR下单
"服务商" -> "API收银台" : 支付下单
"API收银台" -> "OPR" : 反查订单
"API收银台" -> "API收银台" : 产品校验等
"API收银台" -> "PP" : (公众号、小程序、生活号)预路由
"PP" -> "FE" : 预路由
"FE" -[#red]> "FE" : 粉丝路由等新零售需求
"FE" -> "路由" : 预路由
"路由" --> "FE" : 预路由返回
"FE" --> "PP" : 预路由返回
"PP" --> "API收银台" : 预路由返回
"API收银台" -> "PP" : 支付下单
"PP" -> "FE" : 支付下单
"FE" -[#red]> "FE" : (无预路由的支付方式)\n粉丝路由等新零售需求
"FE" -> "路由" : 支付下单
"路由" -[#blue]> "FE" : (银行子系统)支付回调
"FE" -[#blue]> "PP" : 支付回调
"PP" -[#blue]> "PP" : 差错处理
"PP" -[#blue]> "OPR" : 支付回调
"OPR" -[#blue]> "OPR" : 计费入账等资金处理
"OPR" -[#blue]> "服务商" : 支付回调
@enduml



=========新零售API收银台
@startuml
actor 服务商
"服务商" -> "新零售" : 支付下单
"新零售" -> "新零售" : 行业线个性化业务
"新零售" -> "中台支付系统" : 支付下单
"中台支付系统" -> "OPR" : 交易下单
"OPR" --> "中台支付系统" : 交易下单返回
"中台支付系统" -> "路由通道" : 支付下单
"路由通道" --> "中台支付系统" : 返回下单结果
"中台支付系统" --> "新零售" : 返回下单结果
"新零售" --> "服务商" : 返回下单结果

"路由通道" -[#blue]> "中台支付系统" : 支付回调
"中台支付系统" -[#blue]> "OPR" : 支付回调
"中台支付系统" -[#blue]> "新零售" : 支付回调(同步状态)
"OPR" -[#blue]> "OPR" : 计费入账等资金处理
"OPR" -[#blue]> "服务商" : 支付回调
@enduml


============1期：粉丝路由解耦

@startuml
title  新零售入网：重复进件业务时序图（同步到FE）
actor 服务商
"服务商" -> "xls-netin" : 公众号配置(重复进件，传入reportId)
"xls-netin" -> "xls-netin" : 生成虚拟商编
"xls-netin" -> "自动报备" : 虚拟商编报备
"自动报备" -> "路由" : 虚拟商编报备
"路由" --> "自动报备" : 报备返回
"自动报备" --> "xls-netin" : 报备返回
"xls-netin" -> "xls-netin" : 粉丝路由关系落库(商编、reportId、虚拟商编等)
"xls-netin" -> "FE" : 同步粉丝路由关系(商编、reportId、虚拟商编等)
"xls-netin" --> "服务商" : 返回配置受理成功

"xls-netin" -> "自动报备" : (定时触发)虚拟商编配置
"自动报备" -> "路由" : 配置
"路由" --> "自动报备" : 配置返回
"自动报备" --> "xls-netin" : 配置返回

"xls-netin" -> "自动报备" : (定时触发)虚拟商编挂靠
"自动报备" -> "路由" : 挂靠
"路由" --> "自动报备" : 挂靠返回
"自动报备" --> "xls-netin" : 挂靠返回
@enduml


@startuml
title  产品中心：聚合支付下单接口时序图
"服务商" -> "收银台" : 支付下单
"收银台" -> "PP" : 支付下单
"PP" -> "FE" : 支付下单
"FE" -> "FE" : 粉丝路由
"FE" -> "路由" : 支付下单
"路由" --> "FE" : 返回下单结果
"FE" --> "PP" : 返回下单结果
"PP" --> "收银台" : 返回下单结果
"收银台" --> "服务商" : 返回下单结果
@enduml

@startuml
title  产品中心-新零售：聚合支付下单接口时序图
"服务商" -> "收银台" : 支付下单
"收银台" -> "PP" : 支付下单
"PP" -> "FE" : 支付下单
"FE" -> "xls-netin" : 调用粉丝路由接口
"xls-netin" -> "FE" : 返回粉丝路由结果
"FE" -> "路由" : 支付下单
"路由" --> "FE" : 返回下单结果
"FE" --> "PP" : 返回下单结果
"PP" --> "收银台" : 返回下单结果
"收银台" --> "服务商" : 返回下单结果
@enduml
