@startuml
title 交易
"用户" -> "易钱包" : 请求交易
"易钱包" -> "postrx" : 请求交易
"postrx" -> "bpos" : 区域编码路由
"postrx" <-- "bpos" : 返回路由结果
"postrx" -> "路由" : 请求交易
"postrx" <-- "路由" : 返回
"易钱包" <-- "postrx" : 返回
"用户" <-- "易钱包" : 返回
@enduml













