@startuml
title 交易订单推送
"商户" -> "前置1.0系统" : 请求订单推送
"前置1.0系统" -> "前置1.0系统" : 保存订单
"前置1.0系统" -> "前置1.0系统" : 发送到队列
"商户" <-- "前置1.0系统" : 返回
@enduml

@startuml
title 订单推送异步处理

"前置1.0系统" -> "加签验签系统" : 查询银行订单
"加签验签系统" -> "前置1.0系统" : 查单返回

"前置1.0系统" -> "OPR_FRONT" : 下单
"OPR_FRONT" -> "前置1.0系统" : 下单返回

"前置1.0系统" -> "营销系统" : 营销扣账
"营销系统" -> "前置1.0系统" : 营销扣账返回

"前置1.0系统" -> "OPR_FRONT" : 支付回调
"OPR_FRONT" -> "前置1.0系统" : 回调返回

@enduml