@startuml
title 退款请求
actor "商户"
"商户" -> "前置2.0系统" : 退款请求
"前置2.0系统" -> "前置2.0系统" : 查询原交易订单、业务校验
"前置2.0系统" -> "OPR" : 请求扣账(含退款分账)
"OPR" --> "前置2.0系统" : 返回扣账结果
"前置2.0系统" -> "通道" : 请求退款
"通道" --> "前置2.0系统" : 返回退款受理结果
"前置2.0系统" --> "前置2.0系统" : 创建退款请求记录(此前两步骤失败也创建)
"前置2.0系统" --> "商户" : 返回退款受理结果
@enduml

@startuml
title 退款结果查询
actor "商户"
"前置2.0系统" <-- "通道" : 回调退款结果
"前置2.0系统" -> "前置2.0系统" : 更新退款请求状态
"商户" -> "前置2.0系统" : 退款查询请求
"前置2.0系统" -> "前置2.0系统" : 业务校验、查询退款请求记录
"前置2.0系统" --> "商户" : 返回退款结果
@enduml

@startuml
title 退款结果回调
actor "商户"
"前置2.0系统" <-- "通道" : 回调退款结果
"前置2.0系统" -> "前置2.0系统" : 更新退款请求状态
"商户" <-- "前置2.0系统" : 回调退款结果
@enduml
