@startuml
actor 商户
collections "银联(开放平台)"
participant "易宝(API前置平台)"
collections "易宝(OPR、PP等系统)"
collections "银联、网联等(通道)"

商户 -> "银联(开放平台)" : 正向请求
"银联(开放平台)" -> "易宝(API前置平台)" : 正向请求
"易宝(API前置平台)" -> "易宝(OPR、PP等系统)" : 正向请求
"易宝(OPR、PP等系统)" -> "银联、网联等(通道)" : 正向请求

"银联、网联等(通道)" --> "易宝(OPR、PP等系统)" : 返回结果
"易宝(OPR、PP等系统)" --> "易宝(API前置平台)" : 返回结果
"易宝(API前置平台)" --> "银联(开放平台)" : 返回结果
"银联(开放平台)" --> 商户 : 返回结果
@enduml

@startuml
actor 商户
collections "银联(开放平台)"
participant "易宝(API前置平台)"
collections "易宝(OPR、PP等系统)"
collections "银联、网联等(通道)"

"银联、网联等(通道)" --> "易宝(OPR、PP等系统)" : 逆向请求
"易宝(OPR、PP等系统)" --> "易宝(API前置平台)" : 逆向请求
"易宝(API前置平台)" --> "银联(开放平台)" : 逆向请求
"银联(开放平台)" --> 商户 : 逆向请求
@enduml

@startuml
"YOP" -> "聚合前置平台" : 商户信息录入、修改、查询、微信参数配置等
"聚合前置平台" -> "入网子系统" : 商户入网等
"入网子系统" --> "聚合前置平台" : 返回商编等
"聚合前置平台" -> "配置中心" : 产品开通
"配置中心" --> "聚合前置平台" : 接口返回
"聚合前置平台" -> "计费中心" : 配置费率
"计费中心" --> "聚合前置平台" : 接口返回
"聚合前置平台" -> "路由子系统" : 报备、微信参数配置等
"路由子系统" --> "聚合前置平台" : 接口返回
"聚合前置平台" --> "YOP" : 接口返回
"路由子系统" -> "聚合前置平台" : 进件资料审核回调
"聚合前置平台" -> "YOP" : 进件资料审核回调
@enduml

@startuml
"YOP" -> "聚合前置平台" : 商户信息录入、修改、查询、微信参数配置等
"聚合前置平台" -> "路由子系统" : 商户信息录入、修改、查询、微信参数配置等
"路由子系统" --> "聚合前置平台" : 接口返回
"聚合前置平台" --> "YOP" : 接口返回
"路由子系统" -> "聚合前置平台" : 进件资料审核回调
"聚合前置平台" -> "YOP" : 进件资料审核回调
@enduml

@startuml
"YOP" -> "API前置平台" : "主扫下单、被扫下单、js支付下单(公众号等)"
"API前置平台" -> "订单处理器" : 交易下单
"订单处理器" --> "API前置平台" : 接口返回
"API前置平台" -> "PP及下游" : 预路由(仅js支付)
"PP及下游" --> "API前置平台" : 接口返回
"API前置平台" -> "PP及下游" : 聚合支付下单
"PP及下游" --> "API前置平台" : 接口返回
"API前置平台" --> "YOP" : 接口返回
@enduml





